#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/zheap_stub
#
# IDENTIFICATION
#    src/backend/access/zheap_stub/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/zheap_stub
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	undolog_stub.o \
	zheap_handler.o

include $(top_srcdir)/src/backend/common.mk
